vault_version: "1.11.1"
vault_checksum: "sha256:aa2ed532d9a0ecc8635fed63cb3fb6de472b4c01ca622a9a199cd92a046bc73a"
uninstall_vault: "{{uninstall_all or false }}"
update_vault: "{{update_all or false }}"


consul_version: "1.22.2"
consul_checksum: "sha256:e9ad339128e396238f053269bf8f76aeba1b5fada6f6cb60ab19fe70e133acde"
uninstall_consul: "{{uninstall_all or false }}"
update_consul: "{{update_all or false }}"

consul_template_version: "0.41.3"
consul_template_checksum: "sha256:f708323c5a9eeedf1e125662fa1dd3c54f8cadd0758ef2a9a27c7a22e181e93c"
update_consul_template: "{{update_all or false }}"
uninstall_consul_template: "{{uninstall_all or false }}"

nomad_version: "1.11.1"
nomad_checksum: "sha256:8e8fbc9c3ddae39a63f7ed70a99bb4b936bb6e88ed9160ce0e9d36ff2909c1f3"
uninstall_nomad: "{{uninstall_all or false }}"
update_nomad: "{{update_all or false }}"

version_envoy: 1.37.0

nomad_plugin_cni_version: "1.9.0"
nomad_plugin_cni_checksum: "sha256:58c03705426e929658f45a851df15a86d06ef680cacbf3f2dc127731ca265c28"
uninstall_nomad_plugin_cni: "{{uninstall_all or false }}"
update_nomad_plugin_cni: "{{update_all or false }}"


nomad_plugin_consul_cni_version: "1.9.2"
nomad_plugin_consul_cni_checksum: "sha256:0d3e4da8065f2651aeaa696f19f4654d2ae3d0987a5e6ebd4afc8b5b4541717c"
uninstall_nomad_plugin_consul_cni: "{{uninstall_all or false }}"
update_nomad_plugin_consul_cni: "{{update_all or false }}"


nomad_cli_levant_version: "0.3.2"
nomad_cli_levant_checkusum: "sha256:1e06180f8d8327e721e2ad4c9637d1f391034a22709473b8ed8ee19f1cad1570"
uninstall_cli_levant: "{{uninstall_all or false }}"
update_cli_levant: "{{update_all or false }}"

version_wander: "1.1.0"
nomad_cli_wander_checkusum: "sha256:1d82191134ac213a36d1cee0aa9a91fb86de4344cce3649a2f45c5e25f58a1d1"
uninstall_cli_wander: "{{uninstall_all or false }}"
update_cli_wander: "{{update_all or false }}"


version_cfssl: 1.6.5
update_cfssl: "{{update_all or false }}"

version_docker: "29.1.4"
uninstall_docker: false

# docker-compose is not used anymore use docker compose plugin instead
#version_docker_compose: "2.37.3"
#uninstall_compose: false

update_certificates: false

version_nexus: "3.88.0"
version_nexus_initlzr: "1.0.4"
update_nexus: false


version_protoc: "33.4"
version_proto_gen: "1.34.2"
version_proto_gen_js: "3.21.4"
version_proto_gen_validate: "1.1.0"
version_proto_grpc: "1.5.1"
version_proto_grpc_curl: "1.9.1"
uninstall_protoc: "{{uninstall_all or false }}"
update_protoc: "{{update_all or false }}"

version_busy_box_init_container: "1.37.0"
version_multi_stage_apline_container: "3.17.2"
version_grafana_agent_container: "0.44.3"
version_minio: "RELEASE.2025-04-22T22-12-26Z"
version_minio_mc_admin: "RELEASE.2025-04-16T18-13-26Z"
uninstall_minio_admin: "{{uninstall_all or false }}"
update_minio_admin: "{{update_all or false }}"

version_grafana_alloy : "1.12.2"

uninstall_grafana_alloy : "{{uninstall_all or false }}"
# Update is handled by grafana role specify only the new version
#update_grafana_alloy : "{{update_all or false }}"1

validityCaCert: "87600h"
# 1h less than validityCaCert
validityClusterCa: "87599h"
# 1h less than validityClusterCa
validityServerCert: "87598h"
# 1h less than validityServerCert
validityClientCert: "87597h"
