collections:
  - name: community.docker
    version: "4.8.1"
    # Needs for rsync
  - name: ansible.posix
    version: "2.1.0"
  - name: kubernetes.core
    version: "6.1.0"
    # nomad_job
  - name: community.general
    version: "11.4.0"
  - name: grafana.grafana
    version: "6.0.4"
